name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '33 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    continue-on-error: ${{ matrix.pgver == 'master' }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-15 ]
        build_type: [ Debug, Release ]
        compiler: [ clang++, g++ ]
        exclude:
          - os: macos-15
            compiler: g++
      fail-fast: false

    runs-on: ${{ matrix.os }}

    timeout-minutes: 20

    steps:

      - uses: actions/checkout@v3

      - name: Install Boost
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Install Boost
        if: matrix.os == 'macos-15'
        run: |
          brew update
          brew install boost

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --timeout 1000 --force-new-ctest-process --repeat until-pass:10 --output-on-failure -j $(nproc) -C ${{matrix.build_type}}
